; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:ttgo-lora32-v1]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    teckel12/NewPing@^1.9.7
    mcci-catena/MCCI LoRaWAN LMIC library @ ^4.1.1
    adafruit/Adafruit SSD1306 @ ^2.5.11
    adafruit/Adafruit GFX Library @ ^1.11.9
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.1

build_flags =
    -D ARDUINO_LMIC_PROJECT_CONFIG_H_SUPPRESS
    -D CFG_eu868=1
    -D CFG_sx1276_radio=1
    -D LMIC_USE_INTERRUPTS
    -D hal_init=LMIC_hal_initno
